name: Lint JSON files

on:
    push:
        branches:
            - 'master'
    pull_request:
        branches:
            - 'master'

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Node modules
              run: npm install
            - name: Lint
              run: npm run lint
