name: Release Translations
on:
    workflow_dispatch:

jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  path: locales

            - uses: ryand56/r2-upload-action@v1.2
              with:
                  r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
                  r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
                  r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
                  r2-bucket: ${{ secrets.R2_BUCKET }}
                  source-dir: locales/translations
                  destination-dir: locales

    release:
        runs-on: ubuntu-latest
        needs: upload

        steps:
            - id: branch-name
              uses: tj-actions/branch-names@v8

            - id: commit
              uses: prompt/actions-commit-hash@v3

            - uses: ncipollo/release-action@v1
              with:
                  name: '${{ steps.commit.outputs.short }}/${{ steps.branch-name.outputs.current_branch }}'
                  tag: ${{ steps.commit.outputs.short }}
                  token: ${{ secrets.PAT }}
                  makeLatest: true
                  generateReleaseNotes: true
